alter table if exists transaction

    drop constraint if exists FK4utd3b75wfpdmh9rqw5flvnk6;

drop table if exists transaction cascade;

drop table if exists usr cascade;

create table transaction
(
    id      int8 generated by default as identity,
    amount  numeric(19, 2),
    user_id int8,
    primary key (id)
);

create table usr
(
    id   int8 generated by default as identity,
    name varchar(255),
    primary key (id)
);

alter table if exists transaction
    add constraint FK4utd3b75wfpdmh9rqw5flvnk6 foreign key (user_id) references usr