create table if not exists transaction
(
    id      int8 generated by default as identity,
    amount  numeric(19, 2) not null,
    user_id int8,
    primary key (id)
);

create table if not exists usr
(
    id   int8 generated by default as identity,
    name varchar(255) unique not null,
    primary key (id)
);

alter table if exists transaction
    add constraint FK4utd3b75wfpdmh9rqw5flvnk6 foreign key (user_id) references usr